// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8I5djw-0A07V63m714UF-VqlG-VftIyY',
    appId: '1:516303093169:web:0da155914fd99ab56d9190',
    messagingSenderId: '516303093169',
    projectId: 'getting-started-with-idx',
    authDomain: 'getting-started-with-idx.firebaseapp.com',
    storageBucket: 'getting-started-with-idx.appspot.com',
    measurementId: 'G-G9TWB14C4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZ-4YxI69clzdRtOLsnWBwAR6epIqSbo',
    appId: '1:516303093169:android:c4606615080b2e886d9190',
    messagingSenderId: '516303093169',
    projectId: 'getting-started-with-idx',
    storageBucket: 'getting-started-with-idx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzG39_AYFHG6DHPIVJyIHjLH06m6oKvk8',
    appId: '1:516303093169:ios:b26dd27e81a160366d9190',
    messagingSenderId: '516303093169',
    projectId: 'getting-started-with-idx',
    storageBucket: 'getting-started-with-idx.appspot.com',
    iosBundleId: 'com.example.orderItDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzG39_AYFHG6DHPIVJyIHjLH06m6oKvk8',
    appId: '1:516303093169:ios:b26dd27e81a160366d9190',
    messagingSenderId: '516303093169',
    projectId: 'getting-started-with-idx',
    storageBucket: 'getting-started-with-idx.appspot.com',
    iosBundleId: 'com.example.orderItDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8I5djw-0A07V63m714UF-VqlG-VftIyY',
    appId: '1:516303093169:web:76026f37a10ea0e56d9190',
    messagingSenderId: '516303093169',
    projectId: 'getting-started-with-idx',
    authDomain: 'getting-started-with-idx.firebaseapp.com',
    storageBucket: 'getting-started-with-idx.appspot.com',
    measurementId: 'G-8BXVE2NY63',
  );
}
